[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["bundle install", "python3.11 -m pip install -r ml_service/requirements.txt"]

[start]
cmd = "bundle exec rails server -e production"
